- name: "BECFG300.01 create safe user 'udapeople'"
  become: true
  user:
    name: udapeople
    password: {{ upassword | password_hash('sha512') }}
    groups:
      - root
    state: present
    shell: /bin/bash
    createhome: yes
    home: /home/udapeople

- name: "BECFG300.02 give permission to port 80"
  become: true
  shell: |
    sudo apt-get install libcap2-bin
    sudo setcap cap_net_bind_service=+ep /usr/local/bin/node