- name: "install Alertmanager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move alertmanager binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    remote_src: yes
    mode: '0777'

- name: "move amtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool 
    dest: /usr/local/bin/amtool
    remote_src: yes
    mode: '0777'
    
- name: "add alert manager configuration."
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/
  
- name: Allow all access to tcp port 9100
  become: true
  community.general.ufw:
    rule: allow
    port: '9100'
    proto: tcp

- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes